import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<p className={styles.description}>
					Get started by adding <code className={styles.code}>/api?endpoint=##your-url##</code> to your url.
					<br />
					Make sure to replace <code className={styles.code}>##your-url##</code> with the url you want to
					convert. You can generate an .xlsx file by adding <code className={styles.code}>&download</code> at
					the and of the url. your url should then look something like this:{" "}
					<a href="https://reformat.vercel.app/api/?endpoint=https://reformat.vercel.app/api/url&download">
						<code className={styles.code}>
							https://reformat.vercel.app/api?endpoint=https://reformat.vercel.app/api/url&download
						</code>
					</a>
				</p>
			</main>
		</div>
	);
}
